# Generated by Django 3.1.3 on 2020-11-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
