# Generated by Django 2.2.10 on 2020-11-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_auto_20200410_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='tele',
            field=models.IntegerField(default=1),
        ),
    ]
