# Generated by Django 2.2.10 on 2020-11-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0021_auto_20201123_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitaciones',
            old_name='depdir',
            new_name='DireccionDepartamento',
        ),
    ]
