# Generated by Django 2.2.10 on 2020-11-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0022_auto_20201123_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitaciones',
            old_name='DireccionDepartamento',
            new_name='Direccion_Departamento',
        ),
    ]
