# Generated by Django 2.2.10 on 2020-11-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_auto_20201123_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitaciones',
            old_name='Direccion_Departamento',
            new_name='Dirección_Departamento',
        ),
    ]
