# Generated by Django 2.2.10 on 2020-11-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_auto_20201123_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitaciones',
            old_name='descripcion',
            new_name='Descripción',
        ),
        migrations.RenameField(
            model_name='habitaciones',
            old_name='depfechacompra',
            new_name='Fecha_Compra',
        ),
        migrations.RenameField(
            model_name='habitaciones',
            old_name='depnum',
            new_name='Número',
        ),
        migrations.RenameField(
            model_name='habitaciones',
            old_name='depnumdep',
            new_name='Número_Departamento',
        ),
        migrations.RenameField(
            model_name='habitaciones',
            old_name='depprecio',
            new_name='Precio',
        ),
    ]
