# Generated by Django 2.2.10 on 2020-11-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_auto_20201123_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitaciones',
            options={'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
    ]
