# Generated by Django 2.2.10 on 2020-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_auto_20201123_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitaciones',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='cantidad_habitaciones',
            field=models.IntegerField(default=10, verbose_name='cantidad de habitaciones'),
        ),
    ]
