# Generated by Django 2.2.10 on 2020-11-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_auto_20201123_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='ciunombre',
            new_name='Comuna',
        ),
        migrations.RenameField(
            model_name='comuna',
            old_name='comnombre',
            new_name='Cuidad',
        ),
    ]
