# Generated by Django 2.2.10 on 2020-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0030_auto_20201123_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='capacidad',
            field=models.IntegerField(default=1),
        ),
    ]
