# Generated by Django 2.2.10 on 2020-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0031_habitaciones_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
