# Generated by Django 2.2.10 on 2020-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0032_habitaciones_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='habitaciones/'),
        ),
    ]
