# Generated by Django 2.2.10 on 2020-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0033_habitaciones_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_alojamiento',
            name='precio',
            field=models.DecimalField(choices=[(200.0, 200.0), (100.0, 100.0), (300.0, 300.0), (400.0, 400.0), (500.0, 500.0), (600.0, 600.0), (700.0, 700.0), (800.0, 800.0), (900.0, 900.0)], decimal_places=2, max_digits=5),
        ),
    ]
