# Generated by Django 2.2.10 on 2020-11-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0034_auto_20201124_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_habitacion',
            name='noches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cantidadreservas',
            name='limite',
            field=models.IntegerField(default=1, verbose_name='limite'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='cantidad_habitaciones',
            field=models.IntegerField(default=1, verbose_name='cantidad de habitaciones'),
        ),
        migrations.AlterField(
            model_name='habitaciones',
            name='Precio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='precio_pension',
            name='precio',
            field=models.DecimalField(choices=[(150000, 150000), (100000, 100000), (60000, 60000), (0, 0)], decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tipo_alojamiento',
            name='precio',
            field=models.DecimalField(choices=[(200000, 200000), (100000, 100000), (300000, 300000), (400000, 400000), (500000, 500000), (600000, 600000), (700000, 700000), (800000, 800000), (900000, 900000)], decimal_places=2, max_digits=5),
        ),
    ]
