# Generated by Django 2.2.10 on 2020-11-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0035_auto_20201127_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_alojamiento',
            name='precio',
            field=models.DecimalField(choices=[(20000, 20000), (10000, 10000), (30000, 30000), (40000, 40000), (50000, 50000), (60000, 60000), (70000, 70000), (80000, 80000), (90000, 90000)], decimal_places=2, max_digits=5),
        ),
    ]
